import uuid
import pytest
from sqlalchemy.orm import Session
from app.database import SessionLocal
from app.models import User, Project, Document, DocumentChunk
from app.services.vector_store import EmbeddingService, VectorStoreService
from app.services.search_vector import VectorSearchService
from app.services.retrieval import RetrievalService

# Define the 20 technical config queries
QUERIES = [
    "logging.level.org.springframework",
    "spring.jpa.hibernate.ddl-auto",
    "server.port",
    "spring.datasource.url",
    "spring.datasource.username",
    "spring.datasource.password",
    "spring.datasource.driver-class-name",
    "spring.jpa.show-sql",
    "spring.jpa.properties.hibernate.dialect",
    "spring.jackson.date-format",
    "spring.mail.host",
    "spring.mail.port",
    "spring.mail.username",
    "spring.mail.password",
    "spring.security.user.name",
    "spring.security.user.password",
    "spring.servlet.multipart.max-file-size",
    "spring.servlet.multipart.max-request-size",
    "spring.mvc.format.date",
    "spring.cache.type"
]

# Define corresponding target chunks (exact terms)
TARGET_CHUNKS = [
    "Configure the logging level for Spring framework classes using: logging.level.org.springframework = DEBUG",
    "Define the Hibernate schema management strategy with: spring.jpa.hibernate.ddl-auto = update",
    "Change the default port of the embedded server using: server.port = 8080",
    "Set the database connection string: spring.datasource.url = jdbc:postgresql://localhost:5432/phoenix",
    "Set the database username: spring.datasource.username = postgres",
    "Set the database password securely: spring.datasource.password = postgres123",
    "Specify the JDBC driver class name: spring.datasource.driver-class-name = org.postgresql.Driver",
    "Enable Hibernate SQL statement logging to stdout: spring.jpa.show-sql = true",
    "Set the SQL dialect class for Hibernate properties: spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect",
    "Specify the global Jackson date format: spring.jackson.date-format = yyyy-MM-dd HH:mm:ss",
    "Set the outgoing SMTP mail host server: spring.mail.host = smtp.gmail.com",
    "Set the SMTP port for mail server communication: spring.mail.port = 587",
    "Define the username credential for mail sender: spring.mail.username = sender@gmail.com",
    "Define the password credential for SMTP mail: spring.mail.password = smtpPassword",
    "Specify the default spring security username: spring.security.user.name = user",
    "Specify the default spring security user password: spring.security.user.password = secPassWord",
    "Set the maximum file upload size for multipart requests: spring.servlet.multipart.max-file-size = 10MB",
    "Set the maximum total request size for multipart uploads: spring.servlet.multipart.max-request-size = 20MB",
    "Configure the date formatting for spring mvc parameters: spring.mvc.format.date = yyyy-MM-dd",
    "Set the application caching type abstraction: spring.cache.type = redis"
]

# Define 20 semantically similar distractor chunks that share terms but are not the targets
DISTRACTOR_CHUNKS = [
    "The general logging configuration in Spring Boot controls how output is formatted and written to files.",
    "Hibernate ddl-auto has several possible values including create, create-drop, update, validate, and none.",
    "The port of the web server can be changed dynamically by setting the port property in your environment.",
    "The datasource url specifies the connection string for database access including protocol, host, port, and database name.",
    "For connecting to postgres, you need a username and password config, which defaults to postgres in local environments.",
    "Secure your database credentials by encrypting the datasource password in application properties.",
    "The driver class name specifies which database driver to load at runtime, such as org.postgresql.Driver or com.mysql.cj.jdbc.Driver.",
    "Set show-sql to true if you want to log every SQL query generated by hibernate during development.",
    "The hibernate dialect property ensures that the generated SQL syntax is optimized for the specific database engine.",
    "Spring boot serialization defaults can be modified by setting the jackson date format or serialization features.",
    "SMTP server settings for sending emails require configuring the mail host and enabling authentication.",
    "The mail port defaults to 587 for TLS connection or 465 for SSL connection in standard email clients.",
    "Provide the mail username which represents the sender email address when connecting to SMTP server.",
    "The mail password should be an application-specific password if you are using Gmail SMTP.",
    "Spring security default user configures basic authentication username and passwords for API protection.",
    "Do not use the default security user password in production environments, set a custom security configuration instead.",
    "The maximum file size for multipart file uploads defaults to 1MB in Spring Boot, but can be overridden.",
    "Configure multipart request size to allow uploading large files by adjusting the max-request-size parameter.",
    "The MVC date format can be customized in Spring Boot to parse query parameters and path variables.",
    "Spring cache abstraction supports multiple cache types including redis, caffeine, ehcache, hazelcast, and simple."
]

def run_benchmark(db: Session):
    # Setup mock user, project, document
    user_id = uuid.uuid4()
    user = User(
        id=user_id,
        email=f"benchmark-user-{user_id}@example.com",
        password_hash="pass",
        full_name="Benchmark User"
    )
    db.add(user)
    db.flush()

    proj_id = uuid.uuid4()
    project = Project(
        id=proj_id,
        user_id=user_id,
        name="Benchmark Project"
    )
    db.add(project)
    db.flush()

    doc_id = uuid.uuid4()
    doc = Document(
        id=doc_id,
        project_id=proj_id,
        file_name="benchmark_docs.pdf",
        status="READY",
        storage_path="/tmp/benchmark.pdf"
    )
    db.add(doc)
    db.commit()

    try:
        # Load embedding service and insert chunks
        embedding_service = EmbeddingService()
        retrieval_service = RetrievalService(db, embedding_service)

        all_contents = TARGET_CHUNKS + DISTRACTOR_CHUNKS
        chunks_data = []
        for idx, content in enumerate(all_contents):
            chunks_data.append({
                "chunk_index": idx,
                "content": content,
                "metadata": {"type": "target" if idx < 20 else "distractor"}
            })

        print("Generating embeddings for 40 chunks...")
        embeddings = embedding_service.embed_batch(all_contents)
        VectorStoreService.insert_document_chunks(db, doc_id, chunks_data, embeddings)

        print("\n=== Property Key Sensitivity Benchmark ===")
        print(f"{'Query / Config Key':<45} | {'Vector Hit':<10} | {'Hybrid Hit':<10}")
        print("-" * 75)

        vector_hits = 0
        hybrid_hits = 0

        for idx, query in enumerate(QUERIES):
            # Target identifier string for exact matching
            target_substring = QUERIES[idx]

            # 1. Pure Vector Search (limit = 1)
            query_embedding = embedding_service.embed_text(query)
            vector_res = VectorSearchService.search(db, doc_id, query_embedding, limit=1)
            vector_hit = False
            if vector_res:
                top_chunk, _ = vector_res[0]
                if target_substring in top_chunk.content:
                    vector_hit = True
                    vector_hits += 1

            # 2. Hybrid Search (limit = 1, alpha = 0.7)
            hybrid_res, _ = retrieval_service.retrieve_hybrid(doc_id, query, limit=1, alpha=0.7)
            hybrid_hit = False
            if hybrid_res:
                top_chunk, _ = hybrid_res[0]
                if target_substring in top_chunk.content:
                    hybrid_hit = True
                    hybrid_hits += 1

            print(f"{query:<45} | {str(vector_hit):<10} | {str(hybrid_hit):<10}")

        vector_hit_rate = vector_hits / len(QUERIES)
        hybrid_hit_rate = hybrid_hits / len(QUERIES)

        print("-" * 75)
        print(f"{'Hit Rate @ 1':<45} | {vector_hit_rate:<10.2f} | {hybrid_hit_rate:<10.2f}")
        print("===========================================\n")

        return vector_hit_rate, hybrid_hit_rate

    finally:
        # Clean up database
        db.query(DocumentChunk).filter(DocumentChunk.document_id == doc_id).delete()
        db.query(Document).filter(Document.id == doc_id).delete()
        db.query(Project).filter(Project.id == proj_id).delete()
        db.query(User).filter(User.id == user_id).delete()
        db.commit()

def test_property_key_sensitivity():
    db = SessionLocal()
    try:
        vector_hr, hybrid_hr = run_benchmark(db)
        # Assert hybrid search outperforms pure vector search
        assert hybrid_hr > vector_hr, f"Hybrid Hit Rate ({hybrid_hr}) should outperform Vector Hit Rate ({vector_hr})"
        assert hybrid_hr == 1.0, f"Hybrid search should achieve 100% Hit Rate (1.0) on exact-term queries, got {hybrid_hr}"
    finally:
        db.close()

if __name__ == "__main__":
    db = SessionLocal()
    try:
        run_benchmark(db)
    finally:
        db.close()
